# GitHub Actions workflow for a Python application

name: Python application

on:
  push:
    tags: [ "v*.*.*" ]
  # Trigger the workflow on pull requests to main or release branches
  pull_request:
    branches: [ "main", "release/**" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4
    # Set up Python 3.12
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -e .

    - name: Lint with flake8
      run: flake8 . --ignore=E203,E501,E701,W503

    - name: Test with pytest
      run: pytest --cov=. --cov-branch --cov-report=xml --junitxml=junit.xml -o junit_family=legacy tests/

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
